language: node_js
node_js:
  - "0.10"
language: ruby
rvm:
  - 2.2
branches:
  only:
    - develop
    - gh-pages
before_script:
  - gem install compass
  - gem install jekyll
  - npm install -g grunt-cli
script: "grunt --verbose"
