language: node_js
node_js:
  - "0.10"
branches:
  only:
    - develop
    - gh-pages
before_install:
  - rvm install 2.2.2
before_script:
  - gem install compass
  - gem install jekyll
  - npm install -g grunt-cli
script: "grunt --verbose"
